name: Cool-x
on:
  push:
    branches: 
    - main

jobs:
  login:
    runs-on: self-hosted
    steps:
      -
        name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: reg.cchool.xyz
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}

      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: latest  